config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/witch-calculator')

  get '/witch-calculator', to: 'witch_calculator#index'
  post '/calculate-average-kills', to: 'witch_calculator#calculate_average_kills'
  get '/witch-calculator/result', to: 'witch_calculator#result', as: 'witch_calculator_result'

  get '*path' => redirect('/witch-calculator')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/witch_calculator_controller.rb
class WitchCalculatorController < ApplicationController
  def index; end

  def calculate_average_kills
    calculator = WitchCalculatorService.new(params[:persons])
    redirect_to witch_calculator_result_path(average_kills: calculator.calculate_average_kills)
  end

  def result
    @average_kills = params[:average_kills]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/witch_calculator_helper.rb
module WitchCalculatorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WitchCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'witch', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/witch_calculator/index.html.erb
<div class="container">
  <h1 class="text-center">Witch Calculator</h1>
  <%= form_with(model: @witch_calculation, url: calculate_average_kills_path, method: :post, class: "mt-4") do |form| %>
    <div id="persons">
      <div class="person-fields" index=0>
        <div class="row">
          <input class="m10" type="number" name="persons[][age_of_death]" placeholder="Age of Death">
          <input class="m10" type="number" name="persons[][year_of_death]" placeholder="Year of Death">
          <button type="button" class="btn btn-danger remove-person m10">Remove Person</button>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= button_tag 'Add Person', class: "btn btn-primary center", id: "add-person" %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= form.submit 'Calculate', class: "btn btn-primary center" %>
      </div>
    </div>
  <% end %>
</div> 

<%= javascript_pack_tag 'dynamic_form' %>

app/views/witch_calculator/result.html.erb
<div class="container">
  <h1>Witch Calculator Result</h1>
  <div class="row">
    <div class="col">
      <h3 class="center">The average number of people killed on the year of birth is:</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h2 class="center"><%= @average_kills %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'Go Back', witch_calculator_path, class: "btn btn-primary btn-center", onclick: "location.reload()" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <img class="image-center" src="https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_2.0/c_scale,w_400/ncom/en_US/games/switch/l/labyrinth-of-the-witch-switch/description-image" alt="Hero Logo">
    </div>
  </div>
</div>